## LDA with collapsed Gibbs sampling

In [1]:
include("src/lda.jl")
ENV["LINES"] = 40
ENV["COLUMNS"] = 120

dictfile = "data/R3_all_Dictionary.txt"
documentfile = "data/R3-trn-all_run.txt" 
gtfile = "data/R3-Label.txt"
documentfile_test = "data/R3-tst-all_run.txt"
gtfile_test = "data/R3-GT.txt"

gt = readdlm(gtfile, Int64)
document_matrix, dictionary = ldac2docterm(dictfile, documentfile);
document_matrix_test, _ = ldac2docterm(dictfile, documentfile_test);
gt_test = readdlm(gtfile_test, Int64)

# Remove all stopwords
include("src/stopwords.jl")
stopwords = findin(dictionary, stopwords)
document_matrix[:, stopwords] = 0
document_matrix_test[:, stopwords] = 0

0

#### Run with T=3 topics

In [2]:
n_iter = 1000
verbose = true
seed = 1234

alpha = 0.3
beta = 0.3
T = 3
phi, theta = lda(document_matrix, alpha, beta, T,
                    n_iter, verbose, seed);

iteration: 50, elapsed time:9.78s
iteration: 100, elapsed time:20.53s
iteration: 150, elapsed time:30.98s
iteration: 200, elapsed time:44.26s
iteration: 250, elapsed time:55.12s
iteration: 300, elapsed time:66.17s
iteration: 350, elapsed time:77.38s
iteration: 400, elapsed time:89.08s
iteration: 450, elapsed time:103.58s
iteration: 500, elapsed time:114.42s
iteration: 550, elapsed time:125.73s
iteration: 600, elapsed time:136.40s
iteration: 650, elapsed time:147.04s
iteration: 700, elapsed time:159.08s
iteration: 750, elapsed time:170.44s
iteration: 800, elapsed time:184.00s
iteration: 850, elapsed time:194.88s
iteration: 900, elapsed time:205.03s
iteration: 950, elapsed time:214.92s
iteration: 1000, elapsed time:224.77s


### Top 30 words in the 3 topics

In [3]:
# top words in the topics
nwords = 30
topwords = Matrix{Any}(nwords, T)
for itopic in 1:T
    idx = sortperm(phi[:, itopic], rev=true)[1:nwords]
    topwords[:, itopic] = dictionary[idx]
end
topwords

30×3 Array{Any,2}:
 "reuter"         "period"       "lagging"    
 "said"           "jumps"        "rights"     
 "trade"          "storage"      "offer"      
 "year"           "opt"          "putting"    
 "mln"            "peaked"       "lifters"    
 "dlrs"           "activation"   "attendance" 
 "oil"            "adhere"       "reversed"   
 "market"         "bulk"         "detente"    
 "pct"            "fruitful"     "mmi"        
 "told"           "joaquin"      "expiring"   
 "billion"        "infant"       "patricio"   
 "foreign"        "condensates"  "streamlined"
 "today"          "edouard"      "pciac"      
 "bank"           "marckraq"     "packaging"  
 "agreement"      "phyllis"      "lobbies"    
 "prices"         "brazil"       "seas"       
 "countries"      "anti"         "entity"     
 "japan"          "inflation"    "benefitted" 
 "government"     "plan"         "variable"   
 "new"            "limps"        "connections"
 "minister"       "to"           "downgra

#### Topics distributions for document `2`

Seems to be correct (**crude** topic)

*diamond shamrock dia cuts **crude** prices diamond shamrock corp said that effective today it had cut its contract prices for crude oil by **dlrs** a **barrel** the reduction brings its posted price for west texas intermediate to **dlrs** a **barrel** the copany said the price reduction today was made in the light of falling **oil** product prices and a weak **crude** **oil** market a company spokeswoman said diamond is the latest in a line of u s **oil** companies that have cut its contract or posted prices over the last two days citing weak **oil** markets reuter*

In [4]:
theta[2, :]

3-element Array{Float64,1}:
 0.984169  
 0.00791557
 0.00791557

### with T=10 topics

doc `2` still correctly has most weight on the topic that seems related to **oil**

In [5]:
T = 10
phi, theta = lda(document_matrix, alpha, beta, T,
                    n_iter, verbose, seed);

iteration: 50, elapsed time:12.09s
iteration: 100, elapsed time:26.91s
iteration: 150, elapsed time:41.61s
iteration: 200, elapsed time:53.39s
iteration: 250, elapsed time:66.55s
iteration: 300, elapsed time:78.74s
iteration: 350, elapsed time:91.10s
iteration: 400, elapsed time:106.31s
iteration: 450, elapsed time:120.65s
iteration: 500, elapsed time:134.13s
iteration: 550, elapsed time:146.00s
iteration: 600, elapsed time:158.20s
iteration: 650, elapsed time:169.92s
iteration: 700, elapsed time:182.10s
iteration: 750, elapsed time:196.68s
iteration: 800, elapsed time:208.93s
iteration: 850, elapsed time:221.82s
iteration: 900, elapsed time:238.98s
iteration: 950, elapsed time:254.51s
iteration: 1000, elapsed time:267.56s


In [6]:
topwords = Matrix{Any}(nwords, T)
for itopic in 1:T
    idx = sortperm(phi[:, itopic], rev=true)[1:nwords]
    topwords[:, itopic] = dictionary[idx]
end
topwords

30×10 Array{Any,2}:
 "program"      "attract"        "relieving"      "reuter"         …  "laws"           "period"       "lagging"    
 "ends"         "suspension"     "doha"           "said"              "murphy"         "jumps"        "rights"     
 "herman"       "minimizing"     "cheap"          "trade"             "portion"        "storage"      "offer"      
 "francisco"    "hugo"           "whitehall"      "year"              "srb"            "opt"          "putting"    
 "satisfy"      "modestly"       "morocco"        "mln"               "khatib"         "peaked"       "lifters"    
 "appoints"     "conglomerate"   "frequently"     "dlrs"           …  "permitting"     "activation"   "attendance" 
 "overall"      "republican"     "directly"       "oil"               "endorsed"       "adhere"       "reversed"   
 "corporation"  "placement"      "presidential"   "market"            "distorting"     "bulk"         "detente"    
 "chancellor"   "holders"        "pbt"            "p

In [7]:
theta[2, :]

10-element Array{Float64,1}:
 0.0075
 0.0075
 0.0075
 0.9325
 0.0075
 0.0075
 0.0075
 0.0075
 0.0075
 0.0075

#### Most likely topic

In [12]:
topwords[:, 4]

30-element Array{Any,1}:
 "reuter"       
 "said"         
 "trade"        
 "year"         
 "mln"          
 "dlrs"         
 "oil"          
 "market"       
 "pct"          
 "told"         
 "billion"      
 "foreign"      
 "today"        
 "bank"         
 "agreement"    
 "prices"       
 "countries"    
 "japan"        
 "government"   
 "new"          
 "minister"     
 "states"       
 "united"       
 "official"     
 "international"
 "economic"     
 "crude"        
 "week"         
 "exports"      
 "added"        

## using LDA for feature extraction, for classificaton (using kNN)

In [9]:
phi_test, theta_test = lda(document_matrix_test, alpha, beta, T,
                            n_iter, verbose, seed);

iteration: 50, elapsed time:5.34s
iteration: 100, elapsed time:9.62s
iteration: 150, elapsed time:13.80s
iteration: 200, elapsed time:17.97s
iteration: 250, elapsed time:22.17s
iteration: 300, elapsed time:26.33s
iteration: 350, elapsed time:30.67s
iteration: 400, elapsed time:34.87s
iteration: 450, elapsed time:40.96s
iteration: 500, elapsed time:46.57s
iteration: 550, elapsed time:50.94s
iteration: 600, elapsed time:56.10s
iteration: 650, elapsed time:62.49s
iteration: 700, elapsed time:67.84s
iteration: 750, elapsed time:72.62s
iteration: 800, elapsed time:77.97s
iteration: 850, elapsed time:82.96s
iteration: 900, elapsed time:87.87s
iteration: 950, elapsed time:92.87s
iteration: 1000, elapsed time:98.75s


gives a measly ~ 30 % correct classification rate

In [10]:
using Distributions
using Distances

function knn(Xtrain::AbstractArray, labels::AbstractVector,
            Xquery::AbstractArray, k::Int)
    # Simple brute force kNN
    n_train = size(Xtrain, 1)
    n_queries = size(Xquery, 1)
    classification = zeros(Int, n_queries)

    for q in 1:n_queries
        dists = colwise(Euclidean(), Xtrain', Xquery[q, :])
        topclasses = labels[sortperm(dists)[1:k]]
        classification[q] = mode(topclasses)
    end
    
    classification
end

classification = knn(theta, vec(gt), theta_test, 5);

sum(classification .== gt_test) / length(gt_test)

0.30742049469964666

[First of all, LDA is not an identifed model, the topics may have been switched around in the two training passes (commonly known as label switching), so comparing the learned features directly doesn't make sense (though a distance metric is perfectly fine)]

This varies greatly (beteen 10 - 40 %) with different runs of the Gibbs sampler, which seem quite probable considering the Gibbs sampler will only explore local modes of the posterior.

Looking at misclassified documents, etc

In [11]:
find(classification .== gt_test)[1:3], find(classification .!= gt_test)[1:3]

# etc

([5,6,12],[1,2,3])

# Deriving the update rules

use Bayes rule and the conjugacy properties of the Dirichlet/Multinomial, and marginalize to "collapse"